# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06095ec841017a2333a3c99749cec2afeb0d74ca837d0a55f3bdf8b25d9208c93e9576dbf20a5251ff42ef54b5eae3cd42c9a3560c021bf4753f84c62c6380a0

test:
  secret_key_base: 648c6dbd8c707db8ae4a837f5cdad61ad7b6954c451012bfbd6d0d96fc4a0d0f12abc5ad34aa631948d46a13b7720aa708eb1bf79e614a54ab06462024e7cabe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
